### ISSUE TITLE
review bot is often failing because of "Failed to update to revision central"

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#111] opened 2019-09-19 00:00 UTC
E.g. https://phabricator.services.mozilla.com/B115564 for https://phabricator.services.mozilla.com/D46167, or https://phabricator.services.mozilla.com/B115080 for https://phabricator.services.mozilla.com/D46036.

**Comment by sylvestre** [comment] 2019-09-24 14:47
Do we know why we get this error?
Thanks

Le 19/09/2019 à 02:00, Marco a écrit :

**Comment by La0** [comment] 2019-09-24 14:55
We use a default revision as fallback when applying the developer patch. Currently it's `central` (set in Taskcluster secret & easily modifiable).

I cannot reproduce the issue, i always get the bookmark `central` on my different clones, but it seems to be missing sometimes.
I have removed the value from the testing secret yesterday, defaulting to `tip`. Seems to work.
I'll do the same switch on production tommorow if you're ok

**Comment by marco-c** [comment] 2019-09-24 17:12
Can you reproduce on that particular diff?

Maybe this could be fixed by adding the firefoxtree extension to hgrc.

**Comment by La0** [comment] 2019-10-09 09:46
Sentry issue: [CODE-REVIEW-EVENTS-C9](https://sentry.prod.mozaws.net/operations/code-review-events/issues/6427412/)

**Comment by La0** [comment] 2019-10-21 07:58
Closing as [the issue](https://sentry.prod.mozaws.net/operations/code-review-events/issues/6427412/) does not occur anymore after updating the default revision.

**Closed by La0** 2019-10-21 07:58 UTC
Labels: events
