### ISSUE TITLE
Negative value in mozlint tasks crashes the bot

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#265] opened 2019-11-25 18:05 UTC
See https://firefoxci.taskcluster-artifacts.net/Zs4uj7w6Q3ylEuC4fPhhgA/0/public/logs/live_backing.log

**Comment by marco-c** [comment] 2019-11-26 14:41
So I guess #175 was not complete?

**Comment by marco-c** [comment] 2019-11-26 14:43
It's strange because we are supposed to convert -1 to None at https://github.com/mozilla/code-review/blob/210d0109e7764b52feae1bd9655b4b313bd6baad/bot/code_review_bot/__init__.py#L73, and then contains should return early when line is None: https://github.com/mozilla/code-review/blob/210d0109e7764b52feae1bd9655b4b313bd6baad/bot/code_review_bot/revisions.py#L222.

**Comment by La0** [comment] 2019-11-26 14:47
We are just not running the recent code in prod.
Doing a release now seems like a really good idea...

**Comment by marco-c** [comment] 2019-11-26 14:48
Aaaah, that explains everything :P

**Comment by La0** [comment] 2019-11-26 15:39
We should be good now that 1.0.7 has landed

**Comment by marco-c** [comment] 2019-11-26 15:42
So we can close as duplicate of #168.

**Closed by marco-c** 2019-11-26 15:42 UTC
Labels: bot, bug, duplicate

**Comment by La0** [comment] 2019-11-26 15:53
I tested locally with current master, seems to work fine
