### ISSUE TITLE
Retry later when we fail to push to try

### ISSUE THREAD

**Issue by calixteman** [mozilla/code-review#135] opened 2019-10-03 20:38 UTC
For reference:
https://phabricator.services.mozilla.com/D48075/new/

A warning was displayed: Push failed

In such a case the build shouldn't be red and message should explain that the patch isn't the culprit here.

**Comment by marco-c** [comment] 2019-10-03 20:47
I think this was probably caused by a temporary try tree closure, as on Sentry I see the error happened 21 times exactly only in the hour while try was closed (according to https://mozilla-releng.net/treestatus/show/try).

We should probably avoid showing the error completely here.
We could at least check if try is closed and avoid pushing so we don't fail. Even better (but a little more complex to implement) we could re-try periodically.

**Comment by La0** [comment] 2020-01-09 16:25
Pike just got bitten by that issue on https://phabricator.services.mozilla.com/D59320

We should work on that soon @marco-c 
Direct [link to papertrail logs](https://my.papertrailapp.com/systems/a34a1f53-c50a-4106-af94-8cad587076fd/events?focus=1151959880689651719&selected=1151959880689651719)

**Comment by marco-c** [comment] 2020-01-09 16:30
Maybe as a quick workaround, we should avoid logging push failures and just report them to sentry

**Comment by marco-c** [comment] 2022-07-21 10:44
Instead of detecting tree closure, we could simply try to push and, if we fail, we put the build back at the back of the queue and wait a bit before retrying.

**Comment by La0** [comment] 2022-07-28 14:40
The patch would be in libmozevent, when catching [hglib exceptions](https://github.com/mozilla/libmozevent/blob/master/libmozevent/mercurial.py#L379). 

We should either detect the push issues or add a try/except + custom exception in the `push_to_try` method.  In that error case, the build should be added back to the same queue (mercurial), so we simply retry the pull/apply/push cleanly

**Comment by abpostelnicu** [comment] 2022-08-17 13:49
This has been fixed.

**Comment by marco-c** [comment] 2022-08-23 16:18
@abpostelnicu you mentioned that we should probably wait between retries (maybe an exponential wait?) and also maybe detect treeclosure (we can use the treestatus API, https://treestatus.mozilla-releng.net/static/ui/treestatus/show/try) so we don't lose the build if try is closed for a long time. Should we reopen this or file a new issue?

**Comment by marco-c** [comment] 2022-10-20 13:45
This was fixed by the libmozevent update containing https://github.com/mozilla/libmozevent/pull/81.

**Closed by marco-c** 2022-10-20 13:45 UTC
Labels: enhancement, events
