### ISSUE TITLE
After the try run is done, Lando frequently takes more than an hour to clear the "Static analysis and linting are still in progress." indications

### ISSUE THREAD

**Issue by Standard8** [mozilla/code-review#2237] opened 2024-07-04 08:37 UTC
When I [posted this revision yesterday](https://phabricator.services.mozilla.com/D215605), I waited for over an hour after the try run had completed and trying to land via Lando was still saying "Static analysis and linting are still in progress."

This morning, that status has cleared in Lando, though the Phabricator status hasn't updated (see #2236). Though I'm assuming they are separate issues.

Ideally the Lando indicator should be clearing as soon as the try runs are complete.

I have seen this quite frequently, I'm not sure if it is happening 100% of the time, but I'm seeing it happen a lot.

**Comment by marco-c** [comment] 2024-07-24 13:17
Let's close as duplicate of https://github.com/mozilla/code-review/issues/1957.

**Closed by marco-c** 2024-07-24 13:17 UTC
