### ISSUE TITLE
Sentry: Warning: Failed to download a file with an issue

### ISSUE THREAD

**Issue by abpostelnicu** [mozilla/code-review#1574] opened 2023-03-01 13:59 UTC
lately there is  a high yield of [Sentry issues](https://mozilla.sentry.io/issues/3525687112/?alert_rule_id=12607839&alert_timestamp=1674666007535&alert_type=email&environment=production&project=6273985) that it fails to download a file with an issue.  
This is because the corresponding file cannot be found on HGMO.

**Comment by marco-c** [comment] 2023-03-22 10:56
Closing as duplicate of #1495.

**Closed by marco-c** 2023-03-22 10:56 UTC
Labels: duplicate, Sentry
