### ISSUE TITLE
Add API endpoint to list all known issues from a given repository and file path

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#1425] opened 2022-11-24 14:01 UTC
A new endpoint should be exposed as `/repository/<slug>/issues/<path>` to allow listing all known issues for a given repository.

The issues list would be paginated, and sorted by creation time.

As the issues would be regularly cleaned up, we should only retrieve (semi) recent issues.

Some additional filters could be extended:
- a revision date filter, to list issues that happened before a given revision date
- a analyzer / check filter, to list issues produced by a given check (or analyze)

**Comment by marco-c** [comment] 2022-11-25 12:16
Given that for a given Phabricator revision we know its parent revision, we could use the revision instead of the date (i.e. make the API retrieve "all issues that exist at revision X").

**Comment by vrigal** [comment] 2023-02-27 08:31
This is probably a duplicate of #1540 (closed with #1552)

**Closed** 2023-02-27 09:13 UTC
